Use latest version available from server as default in `darkrift pull`
DarkRiftNetworking/darkrift-cli pull request #10
Opened 2019-10-14 19:50 UTC by ktos

Allows empty version in `darkrift pull` command, defaulting to the newest version available from the server (by usage of `GetLatestDarkRiftVersion()` which is currently hard-coded).

2019-10-14 19:54 UTC, ktos commented
Ooops! Sorry! I seems I misunderstood #5 - it should default to *project* version, not the latest version available at all?

My bad. I will force update this branch to the proper solution, later :)

2019-10-15 17:13 UTC, JamJar00 commented
Whoa! I didn't expect to be getting pull requests this fast!

Thank you very much for the contribution, I've added a few comments but this is a really good PR! Thanks! :)

2019-10-16 19:07 UTC, JamJar00 requested changes
I've just moved the `GetLatestDarkRiftVersion` method to `VersionManager` so might be worth moving the `GetCurrentProjectDarkRiftVersion` there as well to keep them together.

2019-10-16 19:07 UTC, JamJar00 commented on Program.cs
> +            [Option('v', HelpText = "Specify the DarkRift version to use.")]
I can't get the issue you were having to reproduce on my machine. `--version` is working fine.

I'm quite hesitant to use `-v` because it's standard practice in CLI tools to use it for a verbose mode. Double check that the following definitely doesn't work for you and if so perhaps we could use something like `-V` for version numbers.
```
darkrift new project my-project --version 1.2.3
```
If you look in the `Project.xml` file you should see `1.2.3` as the  version number.

2019-10-16 19:07 UTC, JamJar00 commented on Program.cs
> +                project.Runtime = new Runtime(GetLatestDarkRiftVersion(), ServerTier.Free, ServerPlatform.Framework);
The behaviour of this currently will be: If the user has a `Project.xml` then they'll pull that version onto their machine, if the user doesn't have a `Project.xml` they'll pull the latest version (when implemented). I'm inclined to say that the second case should be a different command, something like `darkrift pull latest` so that the user doesn't accidenly pull from the wrong directory and not realise they've pulled a different version to that that they expected.

What are your thoughts? We could open the second behaviour as a separate issue if you'd prefer to keep this PR with just the current project version changes?

2019-10-16 19:07 UTC, JamJar00 commented on Program.cs
> +
This method needs XMLdoc like the other methods in the project!

2019-10-16 20:30 UTC, ktos commented on Program.cs
> +                project.Runtime = new Runtime(GetLatestDarkRiftVersion(), ServerTier.Free, ServerPlatform.Framework);
You are right, it makes sense to create a new command for pulling latest. 

But what should be a behaviour when I am trying to put `darkrift pull` in a directory without a project? An error?

2019-10-16 20:36 UTC, ktos commented on Program.cs
> +            [Option('v', HelpText = "Specify the DarkRift version to use.")]
I have checked it out again, and it seems you are right. I am not sure why I was getting the same result as with `darkrift --version`, probably I was trying to do something like `darkrift pull --version` which is not implemented, so it defaults to showing version info.

I will remove this change from my PR.

2019-10-16 20:44 UTC, JamJar00 commented on Program.cs
> +                project.Runtime = new Runtime(GetLatestDarkRiftVersion(), ServerTier.Free, ServerPlatform.Framework);
I think an error would work fine! Just output something in red saying they're not currently in a project!

2019-10-19 09:56 UTC, ktos commented
Sorry, it is very simple, yet it will take me some time to finish - my free time unexpectedly shrinked ;)

2019-10-21 17:10 UTC, JamJar00 commented
No worries!

2019-10-22 20:43 UTC, ktos commented
So I updated the `darkrift pull` command to:

* check if we are in a project directory, and if yes - to use all information from the Project.xml file when no version is given,
* if we are not in a project directory and there is `darkrift pull` without a version specified, it will throw an error,
* if `darkrift pull latest` will be given, the most recent version will be used.

2019-10-24 18:35 UTC, JamJar00 commented
Awesome work! This looks brilliant!

+1 for using `Console.Error` for the error output as well, I'm going to create an issue to move the other error messages to that as they should be using it and not standard out.

I look forward to your next PR! 🤞

2019-10-24 18:36 UTC, merged